version: 2
updates:
  - package-ecosystem: "gomod"
    open-pull-requests-limit: 10
    directory: "/"
    ignore:
      - dependency-name: "github.com/sirupsen/logrus"
      - dependency-name: "k8s.io/api"
      - dependency-name: "k8s.io/apimachinery"
    schedule:
      interval: "daily"
    cooldown:
      default-days: 2
    labels:
      - "kind/dependencies"
      - "bot"
  - package-ecosystem: "github-actions"
    open-pull-requests-limit: 10
    directory: "/"
    schedule:
      interval: "daily"
    cooldown:
      default-days: 2
    labels:
      - "kind/dependencies"
      - "bot"
